/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypkg;

//import Login.MysqlConnect;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Administrator
 */
public class AccountReceivable extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    Statement statement = null;
    private Database db;

    public AccountReceivable() {
        initComponents();
        db = new Database();
        conn = db.CreateDBConnection();
        CustomerFillCombo();
        ProductFillCombo();
    }

    private void clear() {

        recvble_customer_address.setText("");
        recvble_phone.setText("");
        recvble_product_code.setText("");

        recvble_unitprice.setText("");
        recvble_note.setText("");
        recvble_total_price.setText("");
        recvble_quantity.setText("");
        //received_cash.setText("");
        //NetReceivable.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        recvble_product_code = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        recvble_phone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        recvble_customer_address = new javax.swing.JTextField();
        recvble_quantity = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        recvble_unitprice = new javax.swing.JTextField();
        recvble_save_button = new javax.swing.JButton();
        recvble_total_price = new javax.swing.JTextField();
        cmd_clear = new javax.swing.JButton();
        recvble_note = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        customer_name_combo = new javax.swing.JComboBox<>();
        cmd_add_customer = new javax.swing.JButton();
        Product_name_combo = new javax.swing.JComboBox<>();
        cmd_add_product = new javax.swing.JButton();
        receivble_date = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        receivalbe_jtable = new javax.swing.JTable();
        recvble_view_button = new javax.swing.JButton();
        cmd_update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_search_receivable = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel5.setText("Phone number:");

        recvble_product_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recvble_product_codeActionPerformed(evt);
            }
        });

        jLabel8.setText("Quantity:");

        jLabel2.setText("Date:");

        jLabel6.setText("Product Name:");

        jLabel3.setText("Customer Name:");

        jLabel9.setText("Total:");

        jLabel7.setText("Product Code:");

        jLabel4.setText("Address: ");

        recvble_customer_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recvble_customer_addressActionPerformed(evt);
            }
        });

        recvble_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recvble_quantityActionPerformed(evt);
            }
        });

        jLabel11.setText("Unit Price:");

        recvble_save_button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        recvble_save_button.setText("Save");
        recvble_save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recvble_save_buttonActionPerformed(evt);
            }
        });

        recvble_total_price.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recvble_total_priceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recvble_total_priceMouseEntered(evt);
            }
        });
        recvble_total_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recvble_total_priceActionPerformed(evt);
            }
        });
        recvble_total_price.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                recvble_total_priceVetoableChange(evt);
            }
        });

        cmd_clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmd_clear.setText("Clear");
        cmd_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_clearActionPerformed(evt);
            }
        });

        jLabel13.setText("Note:");

        customer_name_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                customer_name_comboItemStateChanged(evt);
            }
        });
        customer_name_combo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                customer_name_comboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        customer_name_combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customer_name_comboMouseClicked(evt);
            }
        });

        cmd_add_customer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmd_add_customer.setText("New");
        cmd_add_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_add_customerActionPerformed(evt);
            }
        });

        Product_name_combo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                Product_name_comboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        Product_name_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product_name_comboActionPerformed(evt);
            }
        });

        cmd_add_product.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmd_add_product.setText("New");
        cmd_add_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_add_productActionPerformed(evt);
            }
        });

        receivble_date.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmd_clear)
                        .addGap(18, 18, 18)
                        .addComponent(recvble_save_button))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recvble_note, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(recvble_quantity)
                                        .addComponent(recvble_product_code)
                                        .addComponent(recvble_phone)
                                        .addComponent(recvble_customer_address)
                                        .addComponent(recvble_unitprice)
                                        .addComponent(recvble_total_price)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(customer_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cmd_add_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Product_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmd_add_product, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 4, Short.MAX_VALUE))
                            .addComponent(receivble_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(receivble_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmd_add_customer)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(customer_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(recvble_customer_address, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(recvble_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Product_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_add_product))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(recvble_product_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recvble_unitprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(recvble_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recvble_total_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recvble_note)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recvble_save_button)
                    .addComponent(cmd_clear))
                .addContainerGap())
        );

        receivalbe_jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receivable ID", "Product Name", "Qanitity", "Unit price", "Total"
            }
        ));
        receivalbe_jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receivalbe_jtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(receivalbe_jtable);

        recvble_view_button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        recvble_view_button.setText("View");
        recvble_view_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recvble_view_buttonActionPerformed(evt);
            }
        });

        cmd_update.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmd_update.setText("Update");
        cmd_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_updateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Account Receivable");

        txt_search_receivable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search_receivableActionPerformed(evt);
            }
        });
        txt_search_receivable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search_receivableKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 255));
        jLabel14.setText("Search");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(recvble_view_button, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmd_update)
                        .addGap(137, 137, 137))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_search_receivable, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 12, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(276, 276, 276))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_search_receivable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmd_update)
                            .addComponent(recvble_view_button))
                        .addGap(110, 110, 110))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void recvble_product_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recvble_product_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recvble_product_codeActionPerformed

    private void recvble_customer_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recvble_customer_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recvble_customer_addressActionPerformed

    private void recvble_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recvble_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recvble_quantityActionPerformed

    private void recvble_save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recvble_save_buttonActionPerformed
        // TODO add your handling code here:

        String recvble_date = receivble_date.getDateFormatString();
        //String customer_name = customer_name_combo.getSelectedItem().toString();
        String customer_address = recvble_customer_address.getText();
        String customer_phone = recvble_phone.getText();
        //String product_name = Product_name_combo.getSelectedItem().toString();
        String product_code = recvble_product_code.getText();
        String quantity = recvble_unitprice.getText();
        String unitprice = recvble_quantity.getText();
        // String note = recvble_note.getText();

        if (recvble_date.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a valid date.");
        } else if (customer_address.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter customer address.");
        } else if (customer_phone.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter customer phone.");
        } else if (product_code.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter product code");
        } else if (quantity.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter product quantity");
        } else if (unitprice.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter product unit Price.");
        } else {

            try {
                int value1 = Integer.parseInt(quantity);
                int value2 = Integer.parseInt(unitprice);
                int value3 = value1 * value2;
                String total = String.valueOf(value3);
                int value4 = Integer.parseInt(total);
                // String cash = received_cash.getText();
                //int value5 = Integer.parseInt(cash);
                //int value6 = value4 - value5;
                // String recvbletotal = String.valueOf(value6);

                String Sql = "insert into  receivable (date, customer_name, customer_address, phone_number, product_code,"
                        + " product_name, quantity, unit_price, debit, total, note) values(?,?,?,?,?,?,?,?,?,?,?)";

                pst = conn.prepareStatement(Sql);
                pst.setString(1, ((JTextField) receivble_date.getDateEditor().getUiComponent()).getText());
                pst.setString(2, customer_name_combo.getSelectedItem().toString());
                pst.setString(3, recvble_customer_address.getText());
                pst.setString(4, recvble_phone.getText());
                pst.setString(5, recvble_product_code.getText());
                pst.setString(6, Product_name_combo.getSelectedItem().toString());
                pst.setString(7, recvble_unitprice.getText());
                pst.setString(8, recvble_quantity.getText());
                pst.setString(9, total);
                pst.setString(10, total);

                pst.setString(11, recvble_note.getText());
                //pst.setString(12, received_cash.getText());
                //pst.setString(13, recvbletotal);

                pst.execute();

                JOptionPane.showMessageDialog(null, "Save");
                clear();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            update_table();

//            try {
//                String Sql = "SELECT product_code, product_name, quantity, unit_price, total FROM  receivable";
//                pst = conn.prepareStatement(Sql);
//                rs = pst.executeQuery();
//                receivalbe_jtable.setModel(DbUtils.resultSetToTableModel(rs));
//
//            } catch (Exception e) {
//
//            }
        }
    }//GEN-LAST:event_recvble_save_buttonActionPerformed

    private void recvble_total_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recvble_total_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recvble_total_priceActionPerformed

    private void cmd_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_cmd_clearActionPerformed

    private void recvble_total_priceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recvble_total_priceMouseEntered
        // TODO add your handling code here:


    }//GEN-LAST:event_recvble_total_priceMouseEntered

    private void recvble_total_priceVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_recvble_total_priceVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_recvble_total_priceVetoableChange

    private void recvble_total_priceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recvble_total_priceMouseClicked
        // TODO add your handling code here:

        String quantity = recvble_unitprice.getText();
        String unitprice = recvble_quantity.getText();
        int value1 = Integer.parseInt(quantity);
        int value2 = Integer.parseInt(unitprice);
        int value3 = value1 * value2;
        String total = String.valueOf(value3);

        recvble_total_price.setText(total);

    }//GEN-LAST:event_recvble_total_priceMouseClicked

    private void receivalbe_jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receivalbe_jtableMouseClicked
        // TODO add your handling code here:
        int i = receivalbe_jtable.getSelectedRow();
        String Table_click = (receivalbe_jtable.getModel().getValueAt(i, 0).toString());

        try {

            String sql = "select * from receivable where receivable_id ='" + Table_click + "'";

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if (rs.next()) {
                String add1 = rs.getString("date");
                receivble_date.setDateFormatString(add1);

                String add2 = rs.getString("customer_name");
                //customer_name_combo.addItem(add2);
                customer_name_combo.setSelectedItem(add2);

                String add3 = rs.getString("customer_address");
                recvble_customer_address.setText(add3);

                String add4 = rs.getString("phone_number");
                recvble_phone.setText(add4);

                String add5 = rs.getString("product_name");
                Product_name_combo.setSelectedItem(add5);

                String add6 = rs.getString("product_code");
                recvble_product_code.setText(add6);

                String add7 = rs.getString("quantity");
                recvble_unitprice.setText(add7);

                String add8 = rs.getString("unit_price");
                recvble_quantity.setText(add8);

                String add9 = rs.getString("total");
                recvble_total_price.setText(add9);

                String add10 = rs.getString("note");
                recvble_note.setText(add10);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_receivalbe_jtableMouseClicked


    private void recvble_view_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recvble_view_buttonActionPerformed
        // TODO add your handling code here:

        update_table();


    }//GEN-LAST:event_recvble_view_buttonActionPerformed

    private void txt_search_receivableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_receivableKeyReleased
        // TODO add your handling code here:

        try {
            String sql = "SELECT receivable_id as 'Receivable ID', product_code as 'Product Code',product_name as 'Product Name', "
                    + "date as 'Date', total as 'Total' FROM receivable "
                    + "WHERE receivable_id = ? or product_code = ? or product_name = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_search_receivable.getText());
            pst.setString(2, txt_search_receivable.getText());
            pst.setString(3, txt_search_receivable.getText());
            rs = pst.executeQuery();

            receivalbe_jtable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_search_receivableKeyReleased

    private void cmd_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_updateActionPerformed
        // TODO add your handling code here:
        //int id = 0;
        String sales_date = receivble_date.getDateFormatString();
        String customer_name = customer_name_combo.getSelectedItem().toString();
        String customer_address = recvble_customer_address.getText();
        String customer_phone = recvble_phone.getText();
        String product_code = recvble_product_code.getText();
        String product_name = Product_name_combo.getSelectedItem().toString();
        String quantity = recvble_unitprice.getText();
        String unit_price = recvble_quantity.getText();
        String total_price = recvble_total_price.getText();
        String note = recvble_note.getText();

        try {

            int i = receivalbe_jtable.getSelectedRow();
            String table_click = (receivalbe_jtable.getModel().getValueAt(i, 0).toString());
            //JOptionPane.showMessageDialog(null, table_click);
            int parse_tableclick = Integer.parseInt(table_click);
            int id = parse_tableclick + 1;
            String id1 = String.valueOf(id);

            String sql = "UPDATE receivable SET date = '" + sales_date + "', "
                    + "customer_name = '" + customer_name + "', "
                    + "customer_address = '" + customer_address + "', "
                    + "phone_number = '" + customer_phone + "', "
                    + "product_code = '" + product_code + "', "
                    + "product_name = '" + product_name + "', "
                    + "quantity = '" + quantity + "', "
                    + "unit_price = '" + unit_price + "', "
                    + "debit = '" + total_price + "', "
                    + "total = '" + total_price + "', "
                    + "note = '" + note + "' "
                    //+ "receivable_id = LAST_INSERT_ID(receivable_id)"
                    + "WHERE  receivable_id = '" + table_click + "' ";

            pst = conn.prepareStatement(sql);
            pst.execute();

            /*  String sql1 = "select last_insert_id() as id";
            pst = conn.prepareStatement(sql);
            pst.execute();

            pst = conn.prepareStatement(sql1);
            rs = pst.executeQuery();

            while (rs.next()) {
                id = rs.getInt("id");
                //JOptionPane.showMessageDialog(null, id);

            } */
            JOptionPane.showMessageDialog(null, "Updated");
            clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        update_table();

        // sales page insert
        /* try {

            String quantity = recvble_quantity.getText();
            String unit_price = recvble_unitprice.getText();
            int value1 = Integer.parseInt(quantity);
            int value2 = Integer.parseInt(unit_price);
            int mul = value1 * value2;
            String total = String.valueOf(mul);
            String rec_id = String.valueOf(id);

            //Insert statement for Debit
            String sql = "INSERT INTO sales(date, customer_name, address,"
                    + " phone_number, product_code, product_name, quantity,"
                    + " unit_price, debit, total, note, receivable_id)"
                    + " VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);

            pst.setString(1, ((JTextField) receivble_date.getDateEditor().getUiComponent()).getText());
            pst.setString(2, customer_name_combo.getSelectedItem().toString());
            pst.setString(3, recvble_customer_address.getText());
            pst.setString(4, recvble_phone.getText());
            pst.setString(5, recvble_product_code.getText());
            pst.setString(6, Product_name_combo.getSelectedItem().toString());
            pst.setString(7, recvble_quantity.getText());
            pst.setString(8, recvble_unitprice.getText());
            pst.setString(9, received_cash.getText());
            pst.setString(10, total);
            pst.setString(11, recvble_note.getText());
            pst.setString(12, rec_id);

            pst.execute();

            //JOptionPane.showMessageDialog(null, "Debit");
            //Insert statement for Credit
            String sql1 = "INSERT INTO sales(date, customer_name, address,"
                    + " phone_number, product_code, product_name, quantity,"
                    + " unit_price, credit, total, note, receivable_id)"
                    + " VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
            pst1 = conn.prepareStatement(sql1);

            pst1.setString(1, ((JTextField) receivble_date.getDateEditor().getUiComponent()).getText());
            pst1.setString(2, customer_name_combo.getSelectedItem().toString());
            pst1.setString(3, recvble_customer_address.getText());
            pst1.setString(4, recvble_phone.getText());
            pst1.setString(5, recvble_product_code.getText());
            pst1.setString(6, Product_name_combo.getSelectedItem().toString());
            pst1.setString(7, recvble_quantity.getText());
            pst1.setString(8, recvble_unitprice.getText());
            pst1.setString(9, received_cash.getText());
            pst1.setString(10, total);
            pst1.setString(11, recvble_note.getText());
            pst1.setString(12, rec_id);
            pst1.execute();

            JOptionPane.showMessageDialog(null, "successfull!");
            clear();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }*/
    }//GEN-LAST:event_cmd_updateActionPerformed

    private void txt_search_receivableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search_receivableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search_receivableActionPerformed

    private void cmd_add_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_add_customerActionPerformed
        // TODO add your handling code here:

        CustomerJFrame cf = new CustomerJFrame();
        cf.setVisible(true);
    }//GEN-LAST:event_cmd_add_customerActionPerformed

    private void cmd_add_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_add_productActionPerformed
        // TODO add your handling code here:

        ProductJFrame pf = new ProductJFrame();
        pf.setVisible(true);
    }//GEN-LAST:event_cmd_add_productActionPerformed

    private void customer_name_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_customer_name_comboItemStateChanged
        // TODO add your handling code here:
        // customer_name_combo.getSelectedItem().toString();
    }//GEN-LAST:event_customer_name_comboItemStateChanged

    private void customer_name_comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_name_comboMouseClicked
        // TODO add your handling code here:
        CustomerFillCombo();
    }//GEN-LAST:event_customer_name_comboMouseClicked

    private void customer_name_comboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_customer_name_comboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String temp = (String) customer_name_combo.getSelectedItem();
        String sql = "select * from customer where name = ?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, temp);
            rs = pst.executeQuery();

            if (rs.next()) {
                String add1 = rs.getString("address");
                recvble_customer_address.setText(add1);
                String add2 = rs.getString("cell_phone");
                recvble_phone.setText(add2);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_customer_name_comboPopupMenuWillBecomeInvisible

    private void Product_name_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product_name_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Product_name_comboActionPerformed

    private void Product_name_comboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_Product_name_comboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:

        String temp = (String) Product_name_combo.getSelectedItem();
        String sql = "select * from product where p_name = ?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, temp);
            rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("p_code");
                recvble_product_code.setText(add1);
                String add2 = rs.getString("unit_price");
                recvble_unitprice.setText(add2);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_Product_name_comboPopupMenuWillBecomeInvisible

    public void CustomerFillCombo() {

        customer_name_combo.removeAllItems();
        customer_name_combo.addItem("Select");
        try {
            //customer_name_combo = new JComboBox<String>();
            pst = null;
            rs = null;
            String sql = "Select name from customer";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //customer_name_combo.removeAllItems();

            while (rs.next()) {
                String c_name = rs.getString("name");
                //JOptionPane.showMessageDialog(null, c_name);
                customer_name_combo.addItem(c_name);
                //dm.addElement(c_name);

            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void ProductFillCombo() {

        Product_name_combo.removeAllItems();
        Product_name_combo.addItem("Select");
        try {
            String sql = "Select p_name from product";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                String p_name = rs.getString("p_name");
                //JOptionPane.showMessageDialog(null, c_name);
                Product_name_combo.addItem(p_name);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    private void update_table() {
        try {
            String sql = "SELECT receivable_id as 'Receivable ID', "
                    + "product_name as 'Product Name',"
                    + " quantity as 'Quantity', "
                    + "unit_price as 'Unit Price',"
                    + " total as 'Total' FROM receivable";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            receivalbe_jtable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountReceivable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountReceivable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountReceivable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountReceivable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountReceivable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Product_name_combo;
    private javax.swing.JButton cmd_add_customer;
    private javax.swing.JButton cmd_add_product;
    private javax.swing.JButton cmd_clear;
    private javax.swing.JButton cmd_update;
    private javax.swing.JComboBox<String> customer_name_combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable receivalbe_jtable;
    private com.toedter.calendar.JDateChooser receivble_date;
    private javax.swing.JTextField recvble_customer_address;
    private javax.swing.JTextField recvble_note;
    private javax.swing.JTextField recvble_phone;
    private javax.swing.JTextField recvble_product_code;
    private javax.swing.JTextField recvble_quantity;
    private javax.swing.JButton recvble_save_button;
    private javax.swing.JTextField recvble_total_price;
    private javax.swing.JTextField recvble_unitprice;
    private javax.swing.JButton recvble_view_button;
    private javax.swing.JTextField txt_search_receivable;
    // End of variables declaration//GEN-END:variables
}
