/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypkg;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

public class Account_PayableJFrame extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    ResultSet rs = null;

    Database db = new Database();

    public Account_PayableJFrame() {
        initComponents();
        conn = db.CreateDBConnection();

        VendorFillCombo();
        ProductFillCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        txt_quantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_unit_price = new javax.swing.JTextField();
        txt_product_code = new javax.swing.JTextField();
        txt_vendor_phone = new javax.swing.JTextField();
        txt_vendor_address = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_note = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        vendor_name_combo = new javax.swing.JComboBox<>();
        cmd_add_vendor = new javax.swing.JButton();
        product_name_combo = new javax.swing.JComboBox<>();
        cmd_add_product = new javax.swing.JButton();
        txt_payable_date = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        payable_view_table = new javax.swing.JTable();
        btn_view = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txt_search_account_payable = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("ACCOUNT PAYABLE");

        jLabel6.setText("Product Name:");

        jLabel10.setText("Total");

        txt_total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_totalMouseClicked(evt);
            }
        });
        txt_total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_totalKeyPressed(evt);
            }
        });

        txt_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quantityActionPerformed(evt);
            }
        });

        jLabel4.setText("Vendor Address:");

        jLabel7.setText("Product Code:");

        txt_vendor_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vendor_phoneActionPerformed(evt);
            }
        });

        jLabel2.setText("Date:");

        jLabel3.setText("Vendor Name:");

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        jLabel11.setText("Note");

        jLabel9.setText("Quantity:");

        jLabel5.setText("Vendor Phone:");

        jLabel8.setText("Unit Price:");

        txt_note.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noteActionPerformed(evt);
            }
        });

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        vendor_name_combo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                vendor_name_comboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        vendor_name_combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vendor_name_comboMouseClicked(evt);
            }
        });

        cmd_add_vendor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmd_add_vendor.setText("New");
        cmd_add_vendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_add_vendorActionPerformed(evt);
            }
        });

        product_name_combo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                product_name_comboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        product_name_combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_name_comboMouseClicked(evt);
            }
        });

        cmd_add_product.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmd_add_product.setText("New");
        cmd_add_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_add_productActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_clear)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_save))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_vendor_address, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(txt_vendor_phone, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(txt_product_code, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(txt_unit_price, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(txt_quantity, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(txt_total, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                .addComponent(txt_note, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(vendor_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmd_add_vendor))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(product_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmd_add_product))))
                    .addComponent(txt_payable_date, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addComponent(jLabel2)
                                                                    .addComponent(txt_payable_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(8, 8, 8)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(jLabel3)
                                                                    .addComponent(vendor_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(cmd_add_vendor))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                    .addComponent(txt_vendor_address, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                                                    .addComponent(jLabel4))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txt_vendor_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(jLabel5))
                                                        .addGap(31, 31, 31))
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(product_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cmd_add_product)))
                                                .addComponent(txt_product_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_unit_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_note, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_clear))
                .addGap(27, 27, 27))
        );

        payable_view_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product code", "Product Name", "Quantity", "Unit Price", "Total"
            }
        ));
        payable_view_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payable_view_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(payable_view_table);

        btn_view.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_view.setText("View");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(0, 102, 255));
        jLabel12.setText("Search");

        txt_search_account_payable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search_account_payableKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_search_account_payable, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_view)
                                .addGap(18, 18, 18)
                                .addComponent(btn_update)
                                .addGap(99, 99, 99))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_search_account_payable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_view)
                            .addComponent(btn_update))))
                .addGap(60, 60, 60))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_vendor_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vendor_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vendor_phoneActionPerformed

    private void txt_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quantityActionPerformed

    private void txt_noteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noteActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:

        String date = txt_payable_date.getDateFormatString();
        //String vendor_name = vendor_name_combo.getSelectedItem().toString();
        String vendor_address = txt_vendor_address.getText();
        String vendor_phone = txt_vendor_phone.getText();
        // String product_name = product_name_combo.getSelectedItem().toString();
        String product_code = txt_product_code.getText();
        String quantity = txt_unit_price.getText();
        String unit_price = txt_quantity.getText();

        if (date.isEmpty()) {
            JOptionPane.showMessageDialog(null, "please Input Date.");
        } //else if (vendor_name.equals("")) {
        //    JOptionPane.showMessageDialog(null, "please Input vendor name.");
        // }
        else if (vendor_address.equals("")) {
            JOptionPane.showMessageDialog(null, "please Input vendor address.");
        } else if (vendor_phone.isEmpty()) {
            JOptionPane.showMessageDialog(null, "please Input vendor phone number.");
        } else if (product_code.isEmpty()) {
            JOptionPane.showMessageDialog(null, "please Input product code.");
        } //else if (product_name.isEmpty()) {
        //  JOptionPane.showMessageDialog(null, "please Input product name.");
        //}
        else if (quantity.isEmpty()) {
            JOptionPane.showMessageDialog(null, "please Input Quantity.");
        } else if (unit_price.isEmpty()) {
            JOptionPane.showMessageDialog(null, "please Input unit Price");
        } else {

            try {
                int price_parse = Integer.parseInt(unit_price);
                int quantity_parse = Integer.parseInt(quantity);
                int calculate_total = price_parse * quantity_parse;
                String total = String.valueOf(calculate_total);

                //Insert data to credit site.
                String Sql = "insert into payable (date, vendor_name, vendor_address,"
                        + " vendor_phone, product_code,"
                        + " product_name, quantity, unit_price,"
                        + " credit, total, note) values(?,?,?,?,?,?,?,?,?,?,?)";

                pst = conn.prepareStatement(Sql);
                pst.setString(1, ((JTextField) txt_payable_date.getDateEditor().getUiComponent()).getText());
                pst.setString(2, vendor_name_combo.getSelectedItem().toString());
                pst.setString(3, txt_vendor_address.getText());
                pst.setString(4, txt_vendor_phone.getText());
                pst.setString(5, txt_product_code.getText());
                pst.setString(6, product_name_combo.getSelectedItem().toString());
                pst.setString(7, txt_unit_price.getText());
                pst.setString(8, txt_quantity.getText());
                pst.setString(9, total);
                pst.setString(10, total);
                pst.setString(11, txt_note.getText());

                pst.execute();
                JOptionPane.showMessageDialog(null, "Saved!");

                view();
                clear();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_btn_saveActionPerformed

    public void VendorFillCombo() {
        vendor_name_combo.removeAllItems();
        vendor_name_combo.addItem("Select");
        
        try {
            String sql = "Select vendor_name from vendor";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //customer_name_combo.removeAllItems();

            while (rs.next()) {
                String c_name = rs.getString("vendor_name");
                //JOptionPane.showMessageDialog(null, c_name);
                vendor_name_combo.addItem(c_name);
                //dm.addElement(c_name);

            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void ProductFillCombo() {
        product_name_combo.removeAllItems();
        product_name_combo.addItem("Select");
        
        try {
            String sql = "Select p_name from product";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                String p_name = rs.getString("p_name");
                //JOptionPane.showMessageDialog(null, c_name);
                product_name_combo.addItem(p_name);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void txt_totalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_totalKeyPressed
        // TODO add your handling code here:

        //String product_name = txt_product_name.getText();

    }//GEN-LAST:event_txt_totalKeyPressed

    private void txt_totalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_totalMouseClicked
        // TODO add your handling code here:

        String quantity = txt_unit_price.getText();
        String unit_price = txt_quantity.getText();
        int price_parse = Integer.parseInt(unit_price);
        int quantity_parse = Integer.parseInt(quantity);
        int calculate_total = price_parse * quantity_parse;
        String total = String.valueOf(calculate_total);
        txt_total.setText(total);
    }//GEN-LAST:event_txt_totalMouseClicked

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        // TODO add your handling code here:
        view();

    }//GEN-LAST:event_btn_viewActionPerformed

    private void payable_view_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payable_view_tableMouseClicked
        // TODO add your handling code here:

        try {

            int i = payable_view_table.getSelectedRow();
            String Table_click = (payable_view_table.getModel().getValueAt(i, 0).toString());
            String sql = "select * from payable where payable_id='" + Table_click + "'";

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if (rs.next()) {
                String add1 = rs.getString("date");
                txt_payable_date.setDateFormatString(add1);
                //receivble_date.setMaxSelectableDate(add1);

                String add2 = rs.getString("vendor_name");
                vendor_name_combo.setSelectedItem(add2);

                String add3 = rs.getString("vendor_address");
                txt_vendor_address.setText(add3);

                String add4 = rs.getString("vendor_phone");
                txt_vendor_phone.setText(add4);

                String add5 = rs.getString("product_code");
                txt_product_code.setText(add5);

                String add6 = rs.getString("product_name");
                product_name_combo.setSelectedItem(add6);

                String add7 = rs.getString("quantity");
                txt_unit_price.setText(add7);

                String add8 = rs.getString("unit_price");
                txt_quantity.setText(add8);

                String add9 = rs.getString("total");
                txt_total.setText(add9);

                String add10 = rs.getString("note");
                txt_note.setText(add10);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_payable_view_tableMouseClicked

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        clear();

    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        try {
            int i = payable_view_table.getSelectedRow();
            String Table_click = (payable_view_table.getModel().getValueAt(i, 0).toString());
            //String sql = "select * from payable where payable_id='" + Table_click + "'";
            
            String date = txt_payable_date.getDateFormatString();
            String vendor_name = vendor_name_combo.getSelectedItem().toString();
            String vendor_address = txt_vendor_address.getText();
            String vendor_phone = txt_vendor_phone.getText();
            String product_code = txt_product_code.getText();
            String product_name = product_name_combo.getSelectedItem().toString();
            String quantity = txt_unit_price.getText();
            String unit_price = txt_quantity.getText();
            int price_parse = Integer.parseInt(unit_price);
            int quantity_parse = Integer.parseInt(quantity);
            int calculate_total = price_parse * quantity_parse;
            String total = String.valueOf(calculate_total);

            String note = txt_note.getText();

            //Update data to credit site
            String sql = "UPDATE payable SET date = '" + date + "', "
                    + "vendor_name = '" + vendor_name + "',"
                    + " vendor_address = '" + vendor_address + "',"
                    + " vendor_phone = '" + vendor_phone + "',"
                    + " product_code = '" + product_code + "',"
                    + " product_name = '" + product_name + "',"
                    + " quantity = '" + quantity + "',"
                    + " unit_price = '" + unit_price + "',"
                    + "credit = '" + total + "', total = '" + total + "',"
                    + " note = '" + note + "'"
                    + " WHERE  payable_id = '" + Table_click + "' ";
            pst = conn.prepareStatement(sql);
            pst.execute();

           
            

            JOptionPane.showMessageDialog(null, "Updated!");
            clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        view();


    }//GEN-LAST:event_btn_updateActionPerformed

    private void vendor_name_comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendor_name_comboMouseClicked
        // TODO add your handling code here:
        VendorFillCombo();
    }//GEN-LAST:event_vendor_name_comboMouseClicked

    private void vendor_name_comboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_vendor_name_comboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String temp = (String) vendor_name_combo.getSelectedItem();
        String sql = "select * from vendor where vendor_name = ?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, temp);
            rs = pst.executeQuery();

            if (rs.next()) {
                String add1 = rs.getString("vendor_address");
                txt_vendor_address.setText(add1);
                String add2 = rs.getString("cell_phone");
                txt_vendor_phone.setText(add2);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_vendor_name_comboPopupMenuWillBecomeInvisible

    private void cmd_add_vendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_add_vendorActionPerformed
        // TODO add your handling code here:
        VendorJFrame vf = new VendorJFrame();
        vf.setVisible(true);

    }//GEN-LAST:event_cmd_add_vendorActionPerformed

    private void product_name_comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_name_comboMouseClicked
        // TODO add your handling code here:
        ProductFillCombo();
    }//GEN-LAST:event_product_name_comboMouseClicked

    private void product_name_comboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_product_name_comboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
       String temp = (String) product_name_combo.getSelectedItem();
        String sql = "select * from product where p_name = ?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, temp);
            rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("p_code");
                txt_unit_price.setText(add1);
                 String add2 = rs.getString("unit_price");
                txt_unit_price.setText(add2);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_product_name_comboPopupMenuWillBecomeInvisible

    private void cmd_add_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_add_productActionPerformed
        // TODO add your handling code here:
        ProductJFrame pf = new ProductJFrame();
        pf.setVisible(true);

    }//GEN-LAST:event_cmd_add_productActionPerformed

    private void txt_search_account_payableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_account_payableKeyReleased
        // TODO add your handling code here:
        try {
            String sql = "SELECT payable_id as 'Payable ID', product_code as 'Product Code', "
                    + "product_name as 'Product Name', date as 'Date', total as 'Total' "
                    + "FROM payable WHERE payable_id = ? or product_code = ? or product_name = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_search_account_payable.getText());
            pst.setString(2, txt_search_account_payable.getText());
            pst.setString(3, txt_search_account_payable.getText());
            rs = pst.executeQuery();

            payable_view_table.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_search_account_payableKeyReleased

    private void clear() {

        vendor_name_combo.setSelectedItem("");
        txt_vendor_address.setText("");
        txt_vendor_phone.setText("");
        txt_product_code.setText("");
        product_name_combo.setSelectedItem("");
        txt_unit_price.setText("");
        txt_total.setText("");
        txt_quantity.setText("");
        txt_note.setText("");

    }

    private void view() {
        try {
            String Sql = "SELECT payable_id as'Payable ID', product_name as'Product Name', quantity as'Quantity', unit_price as'Unit price', total as'Total' FROM payable";
            pst = conn.prepareStatement(Sql);
            rs = pst.executeQuery();
            payable_view_table.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account_PayableJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account_PayableJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account_PayableJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account_PayableJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Account_PayableJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_view;
    private javax.swing.JButton cmd_add_product;
    private javax.swing.JButton cmd_add_vendor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable payable_view_table;
    private javax.swing.JComboBox<String> product_name_combo;
    private javax.swing.JTextField txt_note;
    private com.toedter.calendar.JDateChooser txt_payable_date;
    private javax.swing.JTextField txt_product_code;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_search_account_payable;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_unit_price;
    private javax.swing.JTextField txt_vendor_address;
    private javax.swing.JTextField txt_vendor_phone;
    private javax.swing.JComboBox<String> vendor_name_combo;
    // End of variables declaration//GEN-END:variables
}
