/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypkg;

//import Login.MysqlConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

public class Pay_Account_PayableJFrame extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    ResultSet rs2 = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    PreparedStatement pst2 = null;
    Statement statement = null;
    private Database db = new Database();
    int db_cash = 0;
    int db_total = 0;
    int id = 0;
    //Hint_text ht;
    Placeholder hint;

    public Pay_Account_PayableJFrame() {
        initComponents();
        conn = db.CreateDBConnection();
        VendorFillCombo();
        ProductFillCombo();
       // ht = new Hint_text();
        hint = new Placeholder();
        hint_method();

    }

    public void hint_method() {
        hint.hint_text(txt_search_payable, hint.getPay_payable_search(), 0);
    }

    /*
    public class Hint_text {

        String payable_search_hint = "Purchase ID / Product code / Product name";

        public String getPayable_search_hint() {
            return payable_search_hint;
        }

        public void setPayable_search_hint(String payable_search_hint) {
            this.payable_search_hint = payable_search_hint;
        }

        String colour1 = "#808080";
        String colour2 = "#000000";

        public void hint_text(JTextField field, String hint_text, int i) {
            if (i == 0) {
                field.setText(hint_text);
                field.setForeground(java.awt.Color.decode(colour1));
            }

        }
    

        public void clcik(JTextField field, String hint_text) {
            if (field.getText().equals(hint_text)) {
                field.setText(" ");
                field.setForeground(java.awt.Color.decode(colour2));

            }
        }

    }
*/
    private void clear() {

        vendor_name_combo.setSelectedItem("");
        txt_vendor_address.setText("");
        txt_vendor_phone.setText("");
        txt_product_code.setText("");
        txt_product_code.setText("");
        txt_unit_price.setText("");
        txt_note.setText("");
        txt_total.setText("");
        txt_quantity.setText("");
        txt_cash_paid.setText("");
        txt_net_payable.setText("");
        lbl_payable_id.setText("");
        //total_paid_lbl.setText("");
        paid_lebel_show.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_product_code = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_vendor_phone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_vendor_address = new javax.swing.JTextField();
        txt_quantity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_unit_price = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        txt_total = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_cash_paid = new javax.swing.JTextField();
        txt_net_payable = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        txt_note = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_paid_date = new com.toedter.calendar.JDateChooser();
        vendor_name_combo = new javax.swing.JComboBox<>();
        cmd_add_vendor = new javax.swing.JButton();
        product_name_combo = new javax.swing.JComboBox<>();
        cmd_add_product = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Payable_view_table = new javax.swing.JTable();
        btn_view = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_search_payable = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lbl_payable_id = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        total_paid_lbl = new javax.swing.JLabel();
        paid_lebel_show = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel5.setText("Phone number:");

        txt_product_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_product_codeActionPerformed(evt);
            }
        });

        jLabel8.setText("Quantity:");

        jLabel2.setText("Date:");

        jLabel6.setText("Product Name:");

        jLabel3.setText("Vendor Name:");

        jLabel9.setText("Total:");

        jLabel7.setText("Product Code:");

        jLabel4.setText("Address: ");

        txt_vendor_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vendor_addressActionPerformed(evt);
            }
        });

        txt_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quantityActionPerformed(evt);
            }
        });

        jLabel10.setText("Net Payble:");

        jLabel11.setText("Unit Price:");

        btn_save.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        txt_total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_totalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_totalMouseEntered(evt);
            }
        });
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        txt_total.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                txt_totalVetoableChange(evt);
            }
        });

        jLabel12.setText("Cash Paid:");

        txt_net_payable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_net_payableMouseClicked(evt);
            }
        });
        txt_net_payable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_net_payableActionPerformed(evt);
            }
        });

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        jLabel13.setText("Note:");

        vendor_name_combo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                vendor_name_comboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        vendor_name_combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vendor_name_comboMouseClicked(evt);
            }
        });

        cmd_add_vendor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmd_add_vendor.setText("New");
        cmd_add_vendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_add_vendorActionPerformed(evt);
            }
        });

        product_name_combo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                product_name_comboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        product_name_combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_name_comboMouseClicked(evt);
            }
        });
        product_name_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_name_comboActionPerformed(evt);
            }
        });

        cmd_add_product.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmd_add_product.setText("New");
        cmd_add_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_add_productActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_clear)
                        .addGap(18, 18, 18)
                        .addComponent(btn_save))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_product_code, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_quantity)
                                .addComponent(txt_vendor_phone)
                                .addComponent(txt_vendor_address)
                                .addComponent(txt_unit_price)
                                .addComponent(txt_total)
                                .addComponent(txt_cash_paid)
                                .addComponent(txt_net_payable)
                                .addComponent(txt_paid_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(product_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmd_add_product))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(vendor_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmd_add_vendor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txt_note)))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_paid_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vendor_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(cmd_add_vendor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_vendor_address, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_vendor_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(cmd_add_product))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(product_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_product_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_unit_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_cash_paid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(txt_net_payable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_note, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_clear))
                .addContainerGap())
        );

        Payable_view_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Code", "Product Name", "Qanitity", "Unit price", "Total"
            }
        ));
        Payable_view_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Payable_view_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Payable_view_table);

        btn_view.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_view.setText("View");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Pay Account Payable ");

        txt_search_payable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_search_payableFocusLost(evt);
            }
        });
        txt_search_payable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_search_payableMouseClicked(evt);
            }
        });
        txt_search_payable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search_payableActionPerformed(evt);
            }
        });
        txt_search_payable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search_payableKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 255));
        jLabel14.setText("Search");

        jLabel15.setText("Total Paid:");

        paid_lebel_show.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_payable_id)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(total_paid_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(paid_lebel_show)))
                                .addGap(87, 87, 87)
                                .addComponent(btn_view, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 26, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(txt_search_payable, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(lbl_payable_id)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_search_payable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(total_paid_lbl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(paid_lebel_show)
                                .addComponent(btn_view)))
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_product_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_product_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_product_codeActionPerformed

    private void txt_vendor_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vendor_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vendor_addressActionPerformed

    private void txt_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quantityActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:

        String recvble_date = txt_paid_date.getDateFormatString();
        //String vendor_name = vendor_name_combo.getSelectedItem().toString();
        String vendor_address = txt_vendor_address.getText();
        String vendor_phone = txt_vendor_phone.getText();
        String product_code = txt_product_code.getText();
        //String product_name = product_name_combo.getSelectedItem().toString();
        String quantity = txt_unit_price.getText();
        String unitprice = txt_quantity.getText();
        String cash = txt_net_payable.getText();
        double cash_parse = Double.valueOf(cash);

        //int value5 = Integer.parseInt(cash);
        //int value6 = value4 - value5;
        //String recvbletotal = String.valueOf(value6);
        if (recvble_date.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid date.");
        } else if (vendor_address.equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter Vlue First.");
        } else if (vendor_phone.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter customer phone.");
        } else if (product_code.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter product code");
        } else if (quantity.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter product quantity");
        } else if (cash_parse < 0) {
            JOptionPane.showMessageDialog(null, "You cannot paid more then purchases price!!");
        } else {

            try {

                int i = Payable_view_table.getSelectedRow();
                String table_click = (Payable_view_table.getModel().getValueAt(i, 0).toString());

                int value1 = Integer.parseInt(quantity);
                int value2 = Integer.parseInt(unitprice);
                int value3 = value1 * value2;
                String total = String.valueOf(value3);
                int value4 = Integer.parseInt(total);

                // Insert data to credit site
                String Sql = "insert into  purchases (date, vendor_name, vendor_address,"
                        + " vendor_phone, product_code,"
                        + " product_name, quantity, unit_price, credit, total, note, "
                        + "payable_id) values(?,?,?,?,?,?,?,?,?,?,?,?)";

                pst = conn.prepareStatement(Sql);
                pst.setString(1, ((JTextField) txt_paid_date.getDateEditor().getUiComponent()).getText());
                pst.setString(2, vendor_name_combo.getSelectedItem().toString());
                pst.setString(3, txt_vendor_address.getText());
                pst.setString(4, txt_vendor_phone.getText());
                pst.setString(5, txt_product_code.getText());
                pst.setString(6, product_name_combo.getSelectedItem().toString());
                pst.setString(7, txt_unit_price.getText());
                pst.setString(8, txt_quantity.getText());
                pst.setString(9, txt_cash_paid.getText());
                pst.setString(10, txt_cash_paid.getText());
                pst.setString(11, txt_note.getText());
                pst.setString(12, table_click);

                pst.execute();

                //Insert data to debit site
                String Sql1 = "insert into  purchases (date, vendor_name, vendor_address,"
                        + " vendor_phone, product_code,"
                        + " product_name, quantity, unit_price, debit, total, note, "
                        + "payable_id) values(?,?,?,?,?,?,?,?,?,?,?,?)";

                pst1 = conn.prepareStatement(Sql1);
                pst1.setString(1, ((JTextField) txt_paid_date.getDateEditor().getUiComponent()).getText());
                pst1.setString(2, vendor_name_combo.getSelectedItem().toString());
                pst1.setString(3, txt_vendor_address.getText());
                pst1.setString(4, txt_vendor_phone.getText());
                pst1.setString(5, txt_product_code.getText());
                pst1.setString(6, product_name_combo.getSelectedItem().toString());
                pst1.setString(7, txt_unit_price.getText());
                pst1.setString(8, txt_quantity.getText());
                pst1.setString(9, txt_cash_paid.getText());
                pst1.setString(10, txt_cash_paid.getText());
                pst1.setString(11, txt_note.getText());
                pst1.setString(12, table_click);

                pst1.execute();

                JOptionPane.showMessageDialog(null, "Saved!");
                clear();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }
    }//GEN-LAST:event_btn_saveActionPerformed

    public void VendorFillCombo() {

        vendor_name_combo.removeAllItems();
        vendor_name_combo.addItem("Select");
        try {
            String sql = "Select vendor_name from vendor";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //customer_name_combo.removeAllItems();

            while (rs.next()) {
                String c_name = rs.getString("vendor_name");
                //JOptionPane.showMessageDialog(null, c_name);
                vendor_name_combo.addItem(c_name);
                //dm.addElement(c_name);

            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void ProductFillCombo() {

        product_name_combo.removeAllItems();
        product_name_combo.addItem("Select");
        try {
            String sql = "Select p_name from product";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                String p_name = rs.getString("p_name");
                //JOptionPane.showMessageDialog(null, c_name);
                product_name_combo.addItem(p_name);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void txt_totalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_totalMouseEntered
        // TODO add your handling code here:


    }//GEN-LAST:event_txt_totalMouseEntered

    private void txt_totalVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_txt_totalVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalVetoableChange

    private void txt_totalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_totalMouseClicked
        // TODO add your handling code here:

        String quantity = txt_unit_price.getText();
        String unitprice = txt_quantity.getText();
        int value1 = Integer.parseInt(quantity);
        int value2 = Integer.parseInt(unitprice);
        int value3 = value1 * value2;
        String total = String.valueOf(value3);

        txt_total.setText(total);

    }//GEN-LAST:event_txt_totalMouseClicked

    private void Payable_view_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Payable_view_tableMouseClicked
        // TODO add your handling code here:
        int id = 0;
        int i = Payable_view_table.getSelectedRow();
        String Table_click = (Payable_view_table.getModel().getValueAt(i, 0).toString());

        try {

            String sql = "select * from payable where payable_id ='" + Table_click + "'";

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if (rs.next()) {
                String add1 = rs.getString("date");
                txt_paid_date.setDateFormatString(add1);

                String add2 = rs.getString("vendor_name");
                vendor_name_combo.setSelectedItem(add2);

                String add3 = rs.getString("vendor_address");
                txt_vendor_address.setText(add3);

                String add4 = rs.getString("vendor_phone");
                txt_vendor_phone.setText(add4);

                String add5 = rs.getString("product_code");
                txt_product_code.setText(add5);

                String add6 = rs.getString("product_name");
                product_name_combo.setSelectedItem(add6);

                String add7 = rs.getString("quantity");
                txt_unit_price.setText(add7);

                String add8 = rs.getString("unit_price");
                txt_quantity.setText(add8);

                String add9 = rs.getString("total");
                txt_total.setText(add9);

                String add10 = rs.getString("note");
                txt_note.setText(add10);

//                String add11 = rs.getString("payable_id");
//                lbl_payable_id.setText(add11);
                String total = txt_total.getText();
                int total_parse = Integer.parseInt(total);
                //String cash = received_cash.getText();
                //int cash_parse = Integer.parseInt(cash);

                total_paid_lbl.setText("");
                paid_lebel_show.setText("");
                txt_net_payable.setText("");
                String sql1 = "select credit from purchases where payable_id ='" + Table_click + "'";
                statement = conn.createStatement();
                pst1 = conn.prepareStatement(sql1);
                rs1 = pst1.executeQuery();

                while (rs1.next()) {
                    id += rs1.getInt("credit");
                    //int total_cash_received = id;

                    String show_total_paid = String.valueOf(id);
                    //JOptionPane.showMessageDialog(null, id);
                    //total_paid_lbl.setText(show_total_paid);
                    paid_lebel_show.setText(show_total_paid);
                    int net_payable = total_parse - id;
                    String recvbletotal = String.valueOf(net_payable);
                    txt_net_payable.setText(recvbletotal);

                }

                if (id == 0) {
                    txt_net_payable.setText(add9);
                    //total_paid_lbl.setText("0");
                    paid_lebel_show.setText("0");
                }
                String cash_paid = paid_lebel_show.getText();
                if (total.equals(cash_paid)) {
                    JOptionPane.showMessageDialog(null, "This Purchases Payment is Completed !");
                    clear();

                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        //get total form payable database
        /*try {
            String sql1 = "select total from purchases where product_code = '" + Table_click + "'";
            pst1 = conn.prepareStatement(sql1);
            rs1 = pst.executeQuery();

            while (rs1.next()) {

                db_cash = rs1.getInt(12);
        
                //JOptionPane.showMessageDialog(null, db_cash);
                //JOptionPane.showMessageDialog(null, db_total);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } */
        //get cash from purchase database
        /*try {
            String sql2 = "select total from purchases where product_code = '" + Table_click + "'";
            pst2 = conn.prepareStatement(sql2);
            rs2 = pst2.executeQuery();

            while (rs2.next()) {
                db_cash = rs2.getInt(12);

                //JOptionPane.showMessageDialog(null, db_cash);
                //JOptionPane.showMessageDialog(null, db_total);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }*/
//        TableModel model = receivalbe_jtable.getModel();
//        receivble_date.setDateFormatString(model.getValueAt(i, 0).toString());
//        recvble_customer_name.setText(model.getValueAt(i, 1).toString());
//        recvble_customer_address.setText(model.getValueAt(i, 2).toString());
//        recvble_phone.setText(model.getValueAt(i, 3).toString());
//        recvble_product_code.setText(model.getValueAt(i, 4).toString());
//        recvble_product_name.setText(model.getValueAt(i, 5).toString());
//        recvble_quantity.setText(model.getValueAt(i, 6).toString());
//        recvble_unitprice.setText(model.getValueAt(i, 7).toString());
//        recvble_total_price.setText(model.getValueAt(i, 8).toString());
//        recvble_note.setText(model.getValueAt(i, 9).toString());

    }//GEN-LAST:event_Payable_view_tableMouseClicked


    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        // TODO add your handling code here:

        view();


    }//GEN-LAST:event_btn_viewActionPerformed

    private void txt_net_payableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_net_payableActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txt_net_payableActionPerformed

    private void txt_net_payableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_net_payableMouseClicked
        // TODO add your handling code here:

        int id = 0;
        int i = Payable_view_table.getSelectedRow();
        String table_click = (Payable_view_table.getModel().getValueAt(i, 0).toString());
        //String total = txt_total.getText();

        try {

            String sql = "select credit from purchases where payable_id = ?";
            statement = conn.createStatement();
            pst = conn.prepareStatement(sql);
            pst.setString(1, table_click);

            rs = pst.executeQuery();

            while (rs.next()) {
                id += rs.getInt("credit");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        String total = txt_total.getText();
        int total_parse = Integer.parseInt(total);
        String cash = txt_cash_paid.getText();
        int cash_parse = Integer.parseInt(cash);
        //int total_cash= db_total+cash_parse;
        int total_cash = id + cash_parse;
        String total_cash_show_lebel = String.valueOf(total_cash);
        total_paid_lbl.setText(total_cash_show_lebel);
        int netpayable = total_parse - total_cash;
        String payable_total = String.valueOf(netpayable);
        txt_net_payable.setText(payable_total);


    }//GEN-LAST:event_txt_net_payableMouseClicked

    private void txt_search_payableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_payableKeyReleased
        // TODO add your handling code here:

        try {
            String sql = "SELECT payable_id as 'Payable Id', product_code as 'Product Code', "
                    + "product_name as 'Product Name', date as 'Date', total as 'Total' "
                    + "FROM payable WHERE payable_id = ? or product_code = ? or product_name = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_search_payable.getText());
            pst.setString(2, txt_search_payable.getText());
            pst.setString(3, txt_search_payable.getText());
            rs = pst.executeQuery();

            Payable_view_table.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_search_payableKeyReleased

    private void txt_search_payableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search_payableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search_payableActionPerformed

    private void vendor_name_comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendor_name_comboMouseClicked
        // TODO add your handling code here:
        VendorFillCombo();
    }//GEN-LAST:event_vendor_name_comboMouseClicked

    private void product_name_comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_name_comboMouseClicked
        // TODO add your handling code here:
        ProductFillCombo();
    }//GEN-LAST:event_product_name_comboMouseClicked

    private void vendor_name_comboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_vendor_name_comboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String temp = (String) vendor_name_combo.getSelectedItem();
        String sql = "select * from vendor where vendor_name = ?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, temp);
            rs = pst.executeQuery();

            if (rs.next()) {
                String add1 = rs.getString("vendor_address");
                txt_vendor_address.setText(add1);
                String add2 = rs.getString("cell_phone");
                txt_vendor_phone.setText(add2);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_vendor_name_comboPopupMenuWillBecomeInvisible

    private void product_name_comboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_product_name_comboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String temp = (String) product_name_combo.getSelectedItem();
        String sql = "select * from product where p_name = ?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, temp);
            rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("p_code");
                txt_product_code.setText(add1);
                String add2 = rs.getString("unit_price");
                txt_unit_price.setText(add2);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_product_name_comboPopupMenuWillBecomeInvisible

    private void cmd_add_vendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_add_vendorActionPerformed
        // TODO add your handling code here:
        VendorJFrame vf = new VendorJFrame();
        vf.setVisible(true);

    }//GEN-LAST:event_cmd_add_vendorActionPerformed

    private void cmd_add_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_add_productActionPerformed
        // TODO add your handling code here:
        ProductJFrame pf = new ProductJFrame();
        pf.setVisible(true);

    }//GEN-LAST:event_cmd_add_productActionPerformed

    private void txt_search_payableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_search_payableFocusLost
        // TODO add your handling code here:

        hint.hint_text(txt_search_payable, hint.getPay_payable_search(), txt_search_payable.getText().trim().length());
        //ht.hint_text(txt_search_payable, ht.getPayable_search_hint(), txt_search_payable.getText().trim().length());

    }//GEN-LAST:event_txt_search_payableFocusLost

    private void txt_search_payableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_search_payableMouseClicked
        // TODO add your handling code here:

        hint.clcik(txt_search_payable, hint.getPay_payable_search());
       // ht.clcik(txt_search_payable, ht.getPayable_search_hint());
    }//GEN-LAST:event_txt_search_payableMouseClicked

    private void product_name_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_name_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_name_comboActionPerformed

    private void view() {
        try {
            String sql = "SELECT payable_id as 'Payable Id', product_name as 'Product Name', quantity as 'Quantity', unit_price as 'Unit Price', total as 'Total' FROM payable";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            Payable_view_table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pay_Account_PayableJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pay_Account_PayableJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pay_Account_PayableJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pay_Account_PayableJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pay_Account_PayableJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Payable_view_table;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_view;
    private javax.swing.JButton cmd_add_product;
    private javax.swing.JButton cmd_add_vendor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_payable_id;
    private javax.swing.JLabel paid_lebel_show;
    private javax.swing.JComboBox<String> product_name_combo;
    private javax.swing.JLabel total_paid_lbl;
    private javax.swing.JTextField txt_cash_paid;
    private javax.swing.JTextField txt_net_payable;
    private javax.swing.JTextField txt_note;
    private com.toedter.calendar.JDateChooser txt_paid_date;
    private javax.swing.JTextField txt_product_code;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_search_payable;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_unit_price;
    private javax.swing.JTextField txt_vendor_address;
    private javax.swing.JTextField txt_vendor_phone;
    private javax.swing.JComboBox<String> vendor_name_combo;
    // End of variables declaration//GEN-END:variables
}
