/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypkg;

//import Login.MysqlConnect;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Administrator
 */
public class Receive_account_receivable extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    ResultSet rs2 = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    PreparedStatement pst2 = null;
    Statement statement = null;
    private Database db;
    int db_cash = 0;
    int db_total = 0;

    public Receive_account_receivable() {
        initComponents();
        db = new Database();
        conn = db.CreateDBConnection();
        CustomerFillCombo();
        ProductFillCombo();
    }

    private void clear() {

        recvble_customer_address.setText("");
        recvble_phone.setText("");
        recvble_product_code.setText("");
        recvble_quantity.setText("");
        recvble_note.setText("");
        recvble_total_price.setText("");
        recvble_unitprice.setText("");
        received_cash.setText("");
        NetReceivable.setText("");

        lbl_total_received_show.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        recvble_product_code = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        recvble_phone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        recvble_customer_address = new javax.swing.JTextField();
        recvble_unitprice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        recvble_quantity = new javax.swing.JTextField();
        recvble_save_button = new javax.swing.JButton();
        recvble_total_price = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        received_cash = new javax.swing.JTextField();
        NetReceivable = new javax.swing.JTextField();
        cmd_clear = new javax.swing.JButton();
        recvble_note = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        customer_name_combo = new javax.swing.JComboBox<>();
        cmd_add_customer = new javax.swing.JButton();
        Product_name_combo = new javax.swing.JComboBox<>();
        cmd_add_product = new javax.swing.JButton();
        receivble_date = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        receivalbe_jtable = new javax.swing.JTable();
        recvble_view_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_search_receivable = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbl_total_received_show = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel5.setText("Phone number:");

        recvble_product_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recvble_product_codeActionPerformed(evt);
            }
        });

        jLabel8.setText("Unit Price:");

        jLabel2.setText("Date:");

        jLabel6.setText("Product Name:");

        jLabel3.setText("Customer Name:");

        jLabel9.setText("Total:");

        jLabel7.setText("Product Code:");

        jLabel4.setText("Address: ");

        recvble_customer_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recvble_customer_addressActionPerformed(evt);
            }
        });

        recvble_unitprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recvble_unitpriceActionPerformed(evt);
            }
        });

        jLabel10.setText("Net Receivable:");

        jLabel11.setText("Quantity:");

        recvble_save_button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        recvble_save_button.setText("Save");
        recvble_save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recvble_save_buttonActionPerformed(evt);
            }
        });

        recvble_total_price.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recvble_total_priceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recvble_total_priceMouseEntered(evt);
            }
        });
        recvble_total_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recvble_total_priceActionPerformed(evt);
            }
        });
        recvble_total_price.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                recvble_total_priceVetoableChange(evt);
            }
        });

        jLabel12.setText(" cash Receive:");

        NetReceivable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NetReceivableMouseClicked(evt);
            }
        });
        NetReceivable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NetReceivableActionPerformed(evt);
            }
        });

        cmd_clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmd_clear.setText("Clear");
        cmd_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_clearActionPerformed(evt);
            }
        });

        jLabel13.setText("Note:");

        customer_name_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                customer_name_comboItemStateChanged(evt);
            }
        });
        customer_name_combo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                customer_name_comboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        customer_name_combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customer_name_comboMouseClicked(evt);
            }
        });

        cmd_add_customer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmd_add_customer.setText("New");
        cmd_add_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_add_customerActionPerformed(evt);
            }
        });

        Product_name_combo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                Product_name_comboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        Product_name_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Product_name_comboActionPerformed(evt);
            }
        });

        cmd_add_product.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmd_add_product.setText("New");
        cmd_add_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_add_productActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmd_clear)
                        .addGap(18, 18, 18)
                        .addComponent(recvble_save_button))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recvble_note, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(recvble_unitprice)
                                        .addComponent(recvble_product_code)
                                        .addComponent(recvble_phone)
                                        .addComponent(recvble_customer_address)
                                        .addComponent(recvble_quantity)
                                        .addComponent(recvble_total_price)
                                        .addComponent(received_cash)
                                        .addComponent(NetReceivable)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(customer_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cmd_add_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Product_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmd_add_product, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 4, Short.MAX_VALUE))
                            .addComponent(receivble_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(receivble_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmd_add_customer)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(customer_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(recvble_customer_address, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(recvble_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Product_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_add_product))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(recvble_product_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recvble_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(recvble_unitprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recvble_total_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(received_cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NetReceivable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recvble_note, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recvble_save_button)
                    .addComponent(cmd_clear))
                .addContainerGap())
        );

        receivalbe_jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receivable ID", "Product Name", "Qanitity", "Unit price", "Total"
            }
        ));
        receivalbe_jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receivalbe_jtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(receivalbe_jtable);

        recvble_view_button.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        recvble_view_button.setText("View");
        recvble_view_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recvble_view_buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Receive Account Receivable");

        txt_search_receivable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search_receivableActionPerformed(evt);
            }
        });
        txt_search_receivable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search_receivableKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 255));
        jLabel14.setText("Search");

        jLabel15.setText("Total Received:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_search_receivable, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_total_received_show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(133, 133, 133)
                        .addComponent(recvble_view_button, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 296, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(252, 252, 252))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_search_receivable, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recvble_view_button)
                            .addComponent(jLabel15)
                            .addComponent(lbl_total_received_show))
                        .addGap(110, 110, 110))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void recvble_product_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recvble_product_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recvble_product_codeActionPerformed

    private void recvble_customer_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recvble_customer_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recvble_customer_addressActionPerformed

    private void recvble_unitpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recvble_unitpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recvble_unitpriceActionPerformed

    private void recvble_save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recvble_save_buttonActionPerformed
        // TODO add your handling code here:

        String recvble_date = receivble_date.getDateFormatString();
        String customer_address = recvble_customer_address.getText();
        String customer_phone = recvble_phone.getText();
        String product_code = recvble_product_code.getText();
        String quantity = recvble_quantity.getText();
        String cash_recieved = received_cash.getText();
        String recvable = NetReceivable.getText();
        double recvpars = Double.parseDouble(recvable);

        if (recvble_date.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid date.");
        } else if (customer_address.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter customer address.");
        } else if (customer_phone.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter customer phone.");
        } else if (product_code.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter product code");
        } else if (quantity.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter product quantity");
        } else if (cash_recieved.equals("")) {
            JOptionPane.showMessageDialog(null, "Please cash.");
        } else if (recvpars < 0) {
            JOptionPane.showMessageDialog(null, "You cannot receive cash more then total price!!");

        } else {
            try {
                int i = receivalbe_jtable.getSelectedRow();
                String table_click = (receivalbe_jtable.getModel().getValueAt(i, 0).toString());

                String sql = "INSERT INTO sales(date, customer_name, address,"
                        + " phone_number, product_code, product_name, quantity,"
                        + " unit_price, debit, total, note, receivable_id)"
                        + " VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";

                pst = conn.prepareStatement(sql);
                pst.setString(1, ((JTextField) receivble_date.getDateEditor().getUiComponent()).getText());
                pst.setString(2, customer_name_combo.getSelectedItem().toString());
                pst.setString(3, recvble_customer_address.getText());
                pst.setString(4, recvble_phone.getText());
                pst.setString(5, recvble_product_code.getText());
                pst.setString(6, Product_name_combo.getSelectedItem().toString());
                pst.setString(7, recvble_quantity.getText());
                pst.setString(8, recvble_unitprice.getText());
                pst.setString(9, received_cash.getText());
                pst.setString(10, received_cash.getText());
                pst.setString(11, recvble_note.getText());
                pst.setString(12, table_click);

                pst.execute();

                //Insert statement for Credit
                String sql1 = "INSERT INTO sales(date, customer_name, address,"
                        + " phone_number, product_code, product_name, quantity,"
                        + " unit_price, credit, total, note, receivable_id)"
                        + " VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";

                pst1 = conn.prepareStatement(sql1);
                pst1.setString(1, ((JTextField) receivble_date.getDateEditor().getUiComponent()).getText());
                pst1.setString(2, customer_name_combo.getSelectedItem().toString());
                pst1.setString(3, recvble_customer_address.getText());
                pst1.setString(4, recvble_phone.getText());
                pst1.setString(5, recvble_product_code.getText());
                pst1.setString(6, Product_name_combo.getSelectedItem().toString());
                pst1.setString(7, recvble_quantity.getText());
                pst1.setString(8, recvble_unitprice.getText());
                pst1.setString(9, received_cash.getText());
                pst1.setString(10, received_cash.getText());
                pst1.setString(11, recvble_note.getText());
                pst1.setString(12, table_click);
                pst1.execute();

                JOptionPane.showMessageDialog(null, "Save!");
                clear();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }
    }//GEN-LAST:event_recvble_save_buttonActionPerformed

    private void recvble_total_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recvble_total_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recvble_total_priceActionPerformed

    private void cmd_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_cmd_clearActionPerformed

    private void recvble_total_priceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recvble_total_priceMouseEntered
        // TODO add your handling code here:


    }//GEN-LAST:event_recvble_total_priceMouseEntered

    private void recvble_total_priceVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_recvble_total_priceVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_recvble_total_priceVetoableChange

    private void recvble_total_priceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recvble_total_priceMouseClicked
        // TODO add your handling code here:

        String quantity = recvble_quantity.getText();
        String unitprice = recvble_unitprice.getText();
        int value1 = Integer.parseInt(quantity);
        int value2 = Integer.parseInt(unitprice);
        int value3 = value1 * value2;
        String total = String.valueOf(value3);

        recvble_total_price.setText(total);

    }//GEN-LAST:event_recvble_total_priceMouseClicked


    private void receivalbe_jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receivalbe_jtableMouseClicked
        // TODO add your handling code here:

        //checkbalance();
        int id = 0;
        int i = receivalbe_jtable.getSelectedRow();
        String Table_click = (receivalbe_jtable.getModel().getValueAt(i, 0).toString());

        try {

            String sql = "select * from receivable where receivable_id ='" + Table_click + "'";

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if (rs.next()) {
                String add1 = rs.getString("date");
                receivble_date.setDateFormatString(add1);

                String add2 = rs.getString("customer_name");
                customer_name_combo.setSelectedItem(add2);

                String add3 = rs.getString("customer_address");
                recvble_customer_address.setText(add3);

                String add4 = rs.getString("phone_number");
                recvble_phone.setText(add4);

                String add5 = rs.getString("product_name");
                Product_name_combo.setSelectedItem(add5);

                String add6 = rs.getString("product_code");
                recvble_product_code.setText(add6);

                String add7 = rs.getString("quantity");
                recvble_quantity.setText(add7);

                String add8 = rs.getString("unit_price");
                recvble_unitprice.setText(add8);

                String add9 = rs.getString("total");
                recvble_total_price.setText(add9);

                String add10 = rs.getString("note");
                recvble_note.setText(add10);
            }

            String total = recvble_total_price.getText();
            int total_parse = Integer.parseInt(total);
            //String cash = received_cash.getText();
            //int cash_parse = Integer.parseInt(cash);

            lbl_total_received_show.setText("");
            NetReceivable.setText("");
            String sql1 = "select debit from sales where receivable_id ='" + Table_click + "'";
            statement = conn.createStatement();
            pst1 = conn.prepareStatement(sql1);
            rs1 = pst1.executeQuery();

            while (rs1.next()) {
                id += rs1.getInt("debit");
                //int total_cash_received = id;

                String show_total_received = String.valueOf(id);
                //JOptionPane.showMessageDialog(null, id);
                lbl_total_received_show.setText(show_total_received);
                int net_receivable = total_parse - id;
                String recvbletotal = String.valueOf(net_receivable);
                NetReceivable.setText(recvbletotal);

            }
            String cash_received = lbl_total_received_show.getText();
            if (total.equals(cash_received)) {
                JOptionPane.showMessageDialog(null, "This Sales Payment is Completed !");
                clear();

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_receivalbe_jtableMouseClicked

    private void checkbalance() {

        int id = 0;
        // String payableId = lbl_receivable_id.getText();
        int i = receivalbe_jtable.getSelectedRow();
        String table_click = (receivalbe_jtable.getModel().getValueAt(i, 0).toString());

        try {

            String sql = "select debit from sales where receivable_id = ?";
            statement = conn.createStatement();
            pst = conn.prepareStatement(sql);
            pst.setString(1, table_click);
            rs = pst.executeQuery();

            while (rs.next()) {
                id += rs.getInt("debit");

            }

            //JOptionPane.showMessageDialog(null, "Updated");
            //clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        String total = recvble_total_price.getText();
        int total_parse = Integer.parseInt(total);
        String cash = received_cash.getText();
        int cash_parse = Integer.parseInt(cash);
        int total_cash_received = id + cash_parse;
        String show_total_received = String.valueOf(total_cash_received);
        lbl_total_received_show.setText(show_total_received);
        int net_receivable = total_parse - total_cash_received;
        String recvbletotal = String.valueOf(net_receivable);
        NetReceivable.setText(recvbletotal);
    }


    private void recvble_view_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recvble_view_buttonActionPerformed
        // TODO add your handling code here:

        update_table();
        /*try {
            String Sql = "SELECT product_code as'Product Code', product_name as'Product Name', quantity as'Quantity', unit_price as'Unit price', total as'Total' FROM receivable";
            pst = conn.prepareStatement(Sql);
            rs = pst.executeQuery();
            receivalbe_jtable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }*/

    }//GEN-LAST:event_recvble_view_buttonActionPerformed

    private void NetReceivableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NetReceivableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NetReceivableActionPerformed

    private void NetReceivableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NetReceivableMouseClicked
        // TODO add your handling code here:

        int id = 0;
        // String payableId = lbl_receivable_id.getText();
        int i = receivalbe_jtable.getSelectedRow();
        String table_click = (receivalbe_jtable.getModel().getValueAt(i, 0).toString());
        String total = recvble_total_price.getText();
        try {

            String sql = "select debit from sales where receivable_id = ?";
            statement = conn.createStatement();
            pst = conn.prepareStatement(sql);
            pst.setString(1, table_click);
            rs = pst.executeQuery();

            while (rs.next()) {
                id += rs.getInt("debit");

            }

            //JOptionPane.showMessageDialog(null, "Updated");
            //clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        int total_parse = Integer.parseInt(total);
        String cash = received_cash.getText();
        int cash_parse = Integer.parseInt(cash);
        int total_cash_received = id + cash_parse;
        String show_total_received = String.valueOf(total_cash_received);
        lbl_total_received_show.setText(show_total_received);
        int net_receivable = total_parse - total_cash_received;
        String recvbletotal = String.valueOf(net_receivable);
        NetReceivable.setText(recvbletotal);


    }//GEN-LAST:event_NetReceivableMouseClicked

    private void txt_search_receivableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_receivableKeyReleased
        // TODO add your handling code here:

        try {
            String sql = "SELECT receivable_id as 'Receivable ID', product_code as 'Product Code',"
                    + " product_name as 'Product Name', "
                    + "date as 'Date', total as 'Total'"
                    + " FROM receivable WHERE receivable_id = ? or product_code = ? or product_name = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_search_receivable.getText());
            pst.setString(2, txt_search_receivable.getText());
            pst.setString(3, txt_search_receivable.getText());
            rs = pst.executeQuery();

            receivalbe_jtable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txt_search_receivableKeyReleased

    private void txt_search_receivableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search_receivableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search_receivableActionPerformed

    private void cmd_add_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_add_customerActionPerformed
        // TODO add your handling code here:

        CustomerJFrame cf = new CustomerJFrame();
        cf.setVisible(true);
    }//GEN-LAST:event_cmd_add_customerActionPerformed

    private void cmd_add_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_add_productActionPerformed
        // TODO add your handling code here:

        ProductJFrame pf = new ProductJFrame();
        pf.setVisible(true);
    }//GEN-LAST:event_cmd_add_productActionPerformed

    private void customer_name_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_customer_name_comboItemStateChanged
        // TODO add your handling code here:
        // customer_name_combo.getSelectedItem().toString();
    }//GEN-LAST:event_customer_name_comboItemStateChanged

    private void customer_name_comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_name_comboMouseClicked
        // TODO add your handling code here:
        CustomerFillCombo();
    }//GEN-LAST:event_customer_name_comboMouseClicked

    private void customer_name_comboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_customer_name_comboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String temp = (String) customer_name_combo.getSelectedItem();
        String sql = "select * from customer where name = ?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, temp);
            rs = pst.executeQuery();

            if (rs.next()) {
                String add1 = rs.getString("address");
                recvble_customer_address.setText(add1);
                String add2 = rs.getString("cell_phone");
                recvble_phone.setText(add2);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_customer_name_comboPopupMenuWillBecomeInvisible

    private void Product_name_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Product_name_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Product_name_comboActionPerformed

    private void Product_name_comboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_Product_name_comboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:

        String temp = (String) Product_name_combo.getSelectedItem();
        String sql = "select * from product where p_name = ?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, temp);
            rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("p_code");
                recvble_product_code.setText(add1);
                String add2 = rs.getString("unit_price");
                recvble_unitprice.setText(add2);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_Product_name_comboPopupMenuWillBecomeInvisible

    public void CustomerFillCombo() {

        customer_name_combo.removeAllItems();
        customer_name_combo.addItem("Select");
        try {
            //customer_name_combo = new JComboBox<String>();
            pst = null;
            rs = null;
            String sql = "Select name from customer";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //customer_name_combo.removeAllItems();

            while (rs.next()) {
                String c_name = rs.getString("name");
                //JOptionPane.showMessageDialog(null, c_name);
                customer_name_combo.addItem(c_name);
                //dm.addElement(c_name);

            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void ProductFillCombo() {
        Product_name_combo.removeAllItems();
        Product_name_combo.addItem("Select");

        try {
            String sql = "Select p_name from product";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                String p_name = rs.getString("p_name");
                //JOptionPane.showMessageDialog(null, c_name);
                Product_name_combo.addItem(p_name);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    private void update_table() {
        try {
            String sql = "SELECT receivable_id as 'Receivable ID', "
                    + "product_name as 'Product Name',"
                    + " quantity as 'Quantity', "
                    + "unit_price as 'Unit Price',"
                    + " total as 'Total' FROM receivable";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            receivalbe_jtable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receive_account_receivable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receive_account_receivable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receive_account_receivable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receive_account_receivable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receive_account_receivable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NetReceivable;
    private javax.swing.JComboBox<String> Product_name_combo;
    private javax.swing.JButton cmd_add_customer;
    private javax.swing.JButton cmd_add_product;
    private javax.swing.JButton cmd_clear;
    private javax.swing.JComboBox<String> customer_name_combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_total_received_show;
    private javax.swing.JTable receivalbe_jtable;
    private com.toedter.calendar.JDateChooser receivble_date;
    private javax.swing.JTextField received_cash;
    private javax.swing.JTextField recvble_customer_address;
    private javax.swing.JTextField recvble_note;
    private javax.swing.JTextField recvble_phone;
    private javax.swing.JTextField recvble_product_code;
    private javax.swing.JTextField recvble_quantity;
    private javax.swing.JButton recvble_save_button;
    private javax.swing.JTextField recvble_total_price;
    private javax.swing.JTextField recvble_unitprice;
    private javax.swing.JButton recvble_view_button;
    private javax.swing.JTextField txt_search_receivable;
    // End of variables declaration//GEN-END:variables
}
