/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypkg;

import java.awt.Toolkit;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author JABA002
 */
public class Test_PurchaseJFrame_Update extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    PreparedStatement pst2 = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    ResultSet rs2 = null;
    private Database db = new Database();
    //object creat for palce holder (hint text in search box)
    Placeholder hint;

    public Test_PurchaseJFrame_Update() {
        initComponents();
        setTitle("AMS:Purchase");
        conn = db.CreateDBConnection();
        // total_price();
        VendorFillCombo();
        ProductFillCombo();
        hint = new Placeholder();
        hint_method();

        // txt_search_purchase.setText("Search");
    }

    //
    public void hint_method() {
        hint.hint_text(txt_search_purchase, hint.getPurchase_search(), 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        txt_note = new javax.swing.JTextField();
        txt_vendor_phone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_unit_price = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_purchase_date = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_vendor_address = new javax.swing.JTextField();
        txt_product_code = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        vendor_name_combo = new javax.swing.JComboBox<>();
        cmd_add_vendor = new javax.swing.JButton();
        product_name_combo = new javax.swing.JComboBox<>();
        cmd_add_product = new javax.swing.JButton();
        btn_add_product_purchase = new javax.swing.JButton();
        btn_update_purchase = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_view_purchase = new javax.swing.JButton();
        btn_delete_purchase = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchase_view_table = new javax.swing.JTable();
        txt_search_purchase = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        multiple_add_purchase_table = new javax.swing.JTable();
        btn_save_purchase = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        total_column_price = new javax.swing.JTextField();
        btn_delete_multiple_jtable = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel9.setText("Quantity:");

        jLabel7.setText("Product Code:");

        txt_quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_quantityKeyReleased(evt);
            }
        });

        jLabel5.setText("Phone:");

        jLabel3.setText("Vendor Name:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Date:");

        txt_purchase_date.setCalendar(txt_purchase_date.getCalendar());
        txt_purchase_date.setComponentPopupMenu(txt_purchase_date.getComponentPopupMenu());
        txt_purchase_date.setDateFormatString("yyyy-MM-dd"); // NOI18N

        jLabel10.setText("Note:");

        jLabel4.setText("Product Name:");

        jLabel8.setText("Total:");

        jLabel2.setText("Address:");

        jLabel6.setText("Unit Price:");

        txt_total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_totalMouseClicked(evt);
            }
        });
        txt_total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_totalKeyPressed(evt);
            }
        });

        vendor_name_combo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                vendor_name_comboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        vendor_name_combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vendor_name_comboMouseClicked(evt);
            }
        });
        vendor_name_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendor_name_comboActionPerformed(evt);
            }
        });

        cmd_add_vendor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmd_add_vendor.setText("New");
        cmd_add_vendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_add_vendorActionPerformed(evt);
            }
        });

        product_name_combo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                product_name_comboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        product_name_combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_name_comboMouseClicked(evt);
            }
        });
        product_name_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_name_comboActionPerformed(evt);
            }
        });

        cmd_add_product.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmd_add_product.setText("New");
        cmd_add_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_add_productActionPerformed(evt);
            }
        });

        btn_add_product_purchase.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_add_product_purchase.setText("Add");
        btn_add_product_purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_product_purchaseActionPerformed(evt);
            }
        });

        btn_update_purchase.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_update_purchase.setText("Update");
        btn_update_purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_purchaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_purchase_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_vendor_address, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_vendor_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_product_code, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_unit_price, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btn_add_product_purchase)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_update_purchase))
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_note, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vendor_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmd_add_vendor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(product_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmd_add_product)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_purchase_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_add_vendor)
                    .addComponent(vendor_name_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txt_vendor_address, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_vendor_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(product_name_combo)
                            .addComponent(cmd_add_product))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_product_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_unit_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_note, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add_product_purchase)
                    .addComponent(btn_update_purchase))
                .addContainerGap())
        );

        btn_view_purchase.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_view_purchase.setText("View");
        btn_view_purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view_purchaseActionPerformed(evt);
            }
        });

        btn_delete_purchase.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_delete_purchase.setText("Delete");
        btn_delete_purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_purchaseActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Pay Due");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btn_view_purchase, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete_purchase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_view_purchase)
                    .addComponent(btn_delete_purchase)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        purchase_view_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Code", "Product Name", "Quantity", "Unit Price", "Total"
            }
        ));
        purchase_view_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchase_view_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(purchase_view_table);

        txt_search_purchase.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_search_purchaseFocusLost(evt);
            }
        });
        txt_search_purchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_search_purchaseMouseClicked(evt);
            }
        });
        txt_search_purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search_purchaseActionPerformed(evt);
            }
        });
        txt_search_purchase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search_purchaseKeyReleased(evt);
            }
        });

        jLabel12.setText("Search");

        multiple_add_purchase_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(multiple_add_purchase_table);

        btn_save_purchase.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_save_purchase.setText("Save");
        btn_save_purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_purchaseActionPerformed(evt);
            }
        });

        jLabel1.setText("Total:");

        total_column_price.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                total_column_priceMouseClicked(evt);
            }
        });
        total_column_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_column_priceActionPerformed(evt);
            }
        });
        total_column_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                total_column_priceKeyPressed(evt);
            }
        });

        btn_delete_multiple_jtable.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_delete_multiple_jtable.setText("Delete");
        btn_delete_multiple_jtable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_multiple_jtableActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Purchase Entry");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_search_purchase, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 50, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btn_save_purchase, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete_multiple_jtable, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(total_column_price, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_search_purchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_save_purchase)
                        .addComponent(btn_delete_multiple_jtable))
                    .addComponent(jLabel1)
                    .addComponent(total_column_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_save_purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_purchaseActionPerformed

        // Invoice ID Generator
        char chars[] = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ".toCharArray();
        int max = 100000000;
        int random = (int) (Math.random() * max);
        StringBuilder sb = new StringBuilder();
        while (random > 0) {
            sb.append(chars[random % chars.length]);
            random /= chars.length;
        }
        String invoice_id = "P-" + sb.toString();

        // Insert Data into purchase table
        DefaultTableModel model = (DefaultTableModel) multiple_add_purchase_table.getModel();

        try {
            int rows = multiple_add_purchase_table.getRowCount();
            String sql = "INSERT INTO purchases(invoice_id, date, vendor_name, vendor_address, vendor_phone, "
                    + "product_code, product_name, quantity, unit_price, credit, total, note) "
                    + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            for (int row = 0; row < rows; row++) {
                Object date = multiple_add_purchase_table.getValueAt(row, 0);
                String vendor_name = (String) multiple_add_purchase_table.getValueAt(row, 1);
                String address = (String) multiple_add_purchase_table.getValueAt(row, 2);
                String phone = (String) multiple_add_purchase_table.getValueAt(row, 3);
                String p_name = (String) multiple_add_purchase_table.getValueAt(row, 4);
                String p_code = (String) multiple_add_purchase_table.getValueAt(row, 5);
                String quantity = (String) multiple_add_purchase_table.getValueAt(row, 6);
                String unit_price = (String) multiple_add_purchase_table.getValueAt(row, 7);
                String total = (String) multiple_add_purchase_table.getValueAt(row, 8);
                String note = (String) multiple_add_purchase_table.getValueAt(row, 9);

                //insert data into credit
                pst.setString(1, invoice_id);
                pst.setString(2, (String) date);
                pst.setString(3, vendor_name);
                pst.setString(4, address);
                pst.setString(5, phone);
                pst.setString(6, p_code);
                pst.setString(7, p_name);
                pst.setString(8, quantity);
                pst.setString(9, unit_price);
                pst.setString(10, total);
                pst.setString(11, total);
                pst.setString(12, note);
                pst.execute();

                //Insert into debit data
                String sql1 = "INSERT INTO purchases(invoice_id, date, vendor_name, vendor_address, vendor_phone, "
                        + "product_code, product_name, quantity, unit_price, debit, total, note) "
                        + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
                pst1 = conn.prepareStatement(sql1);

                pst1.setString(1, invoice_id);
                pst1.setString(2, (String) date);
                pst1.setString(3, vendor_name);
                pst1.setString(4, address);
                pst1.setString(5, phone);
                pst1.setString(6, p_code);
                pst1.setString(7, p_name);
                pst1.setString(8, quantity);
                pst1.setString(9, unit_price);
                pst1.setString(10, total);
                pst1.setString(11, total);
                pst1.setString(12, note);
                pst1.execute();

            }

            JOptionPane.showMessageDialog(null, "Data saved successfull!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        model.setRowCount(0);
        view();
    }//GEN-LAST:event_btn_save_purchaseActionPerformed

    public void VendorFillCombo() {

        vendor_name_combo.removeAllItems();
        vendor_name_combo.addItem("Select");
        try {

            String sql = "Select vendor_name from vendor";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            //customer_name_combo.removeAllItems();

            while (rs.next()) {
                String c_name = rs.getString("vendor_name");
                //JOptionPane.showMessageDialog(null, c_name);
                vendor_name_combo.addItem(c_name);
                //dm.addElement(c_name);

            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void ProductFillCombo() {
        product_name_combo.removeAllItems();
        product_name_combo.addItem("Select");

        try {
            String sql = "Select p_name from product";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                String p_name = rs.getString("p_name");
                //JOptionPane.showMessageDialog(null, c_name);
                product_name_combo.addItem(p_name);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    private void view() {
        try {
            String sql = "SELECT purchase_id as 'Purchase Id', product_name as 'Product Name', "
                    + "quantity as 'Quantity', unit_price as 'Unit Price', total as 'Total' "
                    + "FROM purchases where credit IS NOT NULL ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            purchase_view_table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void btn_update_purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_purchaseActionPerformed
        // TODO add your handling code here:

        String purchases_date = txt_purchase_date.getDateFormatString();
        String vendor_name = vendor_name_combo.getSelectedItem().toString();
        String vendor_address = txt_vendor_address.getText();
        String vendor_phone = txt_vendor_phone.getText();
        String product_code = txt_product_code.getText();
        String product_name = product_name_combo.getSelectedItem().toString();
        String quantity = txt_unit_price.getText();
        String unit_price = txt_quantity.getText();
        String note = txt_note.getText();

        //String value =  "0";
        int row = purchase_view_table.getSelectedRow();
        String table_click = (purchase_view_table.getModel().getValueAt(row, 0).toString());

        //JOptionPane.showMessageDialog(null, table_click);
        int parse_tableclick = Integer.parseInt(table_click);
        int id = parse_tableclick + 1;
        String id1 = String.valueOf(id);
        try {

            int quantity_parse = Integer.parseInt(quantity);
            int unitprice_parse = Integer.parseInt(unit_price);
            int total_price = quantity_parse * unitprice_parse;
            String total = String.valueOf(total_price);

            //Update data to credit site
            String sql = "UPDATE purchases SET date = '" + purchases_date + "',"
                    + " vendor_name = '" + vendor_name + "',"
                    + " vendor_address = '" + vendor_address + "', "
                    + "vendor_phone = '" + vendor_phone + "',"
                    + " product_code = '" + product_code + "', "
                    + "product_name = '" + product_name + "',"
                    + " quantity = '" + quantity + "', "
                    + "unit_price = '" + unit_price + "',"
                    + " credit = '" + total + "',"
                    + "total = '" + total + "', note = '" + note + "'"
                    + " WHERE  purchase_id = '" + table_click + "' ";
            pst = conn.prepareStatement(sql);
            pst.execute();

            // Update data to debit site
            String sql1 = "UPDATE purchases SET date = '" + purchases_date + "',"
                    + " vendor_name = '" + vendor_name + "',"
                    + " vendor_address = '" + vendor_address + "', "
                    + "vendor_phone = '" + vendor_phone + "',"
                    + " product_code = '" + product_code + "', "
                    + "product_name = '" + product_name + "',"
                    + " quantity = '" + quantity + "',"
                    + " unit_price = '" + unit_price + "', "
                    + "debit = '" + total + "',"
                    + "total = '" + total + "',"
                    + " note = '" + note + "'"
                    + " WHERE  purchase_id = '" + id1 + "' ";
            pst1 = conn.prepareStatement(sql1);
            pst1.execute();

            JOptionPane.showMessageDialog(null, "Updated");
            clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        view();

    }//GEN-LAST:event_btn_update_purchaseActionPerformed

    private void btn_view_purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view_purchaseActionPerformed
        // TODO add your handling code here:
        view();
        clear();

    }//GEN-LAST:event_btn_view_purchaseActionPerformed

    private void purchase_view_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchase_view_tableMouseClicked
        // TODO add your handling code here:

        try {
            int row = purchase_view_table.getSelectedRow();
            String table_click = (purchase_view_table.getModel().getValueAt(row, 0).toString());
            String sql = "SELECT * FROM  purchases WHERE purchase_id = '" + table_click + "' ";

            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if (rs.next()) {
                String add1 = rs.getString("date");
                txt_purchase_date.setDateFormatString(add1);

                String add2 = rs.getString("vendor_name");
                vendor_name_combo.setSelectedItem(add2);

                String add3 = rs.getString("vendor_address");
                txt_vendor_address.setText(add3);

                String add4 = rs.getString("vendor_phone");
                txt_vendor_phone.setText(add4);

                String add5 = rs.getString("product_code");
                txt_product_code.setText(add5);

                String add6 = rs.getString("product_name");
                product_name_combo.setSelectedItem(add6);

                String add7 = rs.getString("quantity");
                txt_quantity.setText(add7);

                String add8 = rs.getString("unit_price");
                txt_unit_price.setText(add8);

                String add9 = rs.getString("total");
                txt_total.setText(add9);

                String add10 = rs.getString("note");
                txt_note.setText(add10);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_purchase_view_tableMouseClicked

    private void txt_totalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_totalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalKeyPressed

    private void btn_delete_purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_purchaseActionPerformed
        // TODO add your handling code here:

        int i = purchase_view_table.getSelectedRow();
        String table_click = (purchase_view_table.getModel().getValueAt(i, 0).toString());

        //JOptionPane.showMessageDialog(null, id);
        int parse_click = Integer.parseInt(table_click);
        int next_id = parse_click + 1;
        String id = String.valueOf(next_id);

        int p = JOptionPane.showConfirmDialog(null, "Do you really want to delete!!", "Delete", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            try {
                String sql = "DELETE FROM purchases WHERE purchase_id = ?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, table_click);
                pst.execute();

                String sql1 = "DELETE FROM purchases WHERE purchase_id = ?";
                pst1 = conn.prepareStatement(sql1);
                pst1.setString(1, id);
                pst1.execute();
                JOptionPane.showMessageDialog(null, "Deleted!");
                clear();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            view();
        }

    }//GEN-LAST:event_btn_delete_purchaseActionPerformed

    private void total_price() {
        String quantity = txt_unit_price.getText();
        int quantity_parse = Integer.parseInt(quantity);
        String unit = txt_quantity.getText();
        int unit_parse = Integer.parseInt(unit);
        int total = quantity_parse * unit_parse;
        String result = String.valueOf(total);
        txt_total.setText(result);
    }

    private void txt_totalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_totalMouseClicked
        // TODO add your handling code here:
        String quantity = txt_unit_price.getText();
        int quantity_parse = Integer.parseInt(quantity);
        String unit = txt_quantity.getText();
        int unit_parse = Integer.parseInt(unit);
        int total = quantity_parse * unit_parse;
        String result = String.valueOf(total);
        txt_total.setText(result);
    }//GEN-LAST:event_txt_totalMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Pay_Account_PayableJFrame p = new Pay_Account_PayableJFrame();
        p.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void product_name_comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_name_comboMouseClicked
        // TODO add your handling code here:
        ProductFillCombo();
    }//GEN-LAST:event_product_name_comboMouseClicked

    private void vendor_name_comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendor_name_comboMouseClicked
        // TODO add your handling code here:

        VendorFillCombo();
    }//GEN-LAST:event_vendor_name_comboMouseClicked

    private void cmd_add_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_add_productActionPerformed
        // TODO add your handling code here:
        ProductJFrame pf = new ProductJFrame();
        pf.setVisible(true);
    }//GEN-LAST:event_cmd_add_productActionPerformed

    private void cmd_add_vendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_add_vendorActionPerformed
        // TODO add your handling code here:
        VendorJFrame vf = new VendorJFrame();
        vf.setVisible(true);

    }//GEN-LAST:event_cmd_add_vendorActionPerformed

    private void vendor_name_comboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_vendor_name_comboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String temp = (String) vendor_name_combo.getSelectedItem();
        String sql = "select * from vendor where vendor_name = ?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, temp);
            rs = pst.executeQuery();

            if (rs.next()) {
                String add1 = rs.getString("vendor_address");
                txt_vendor_address.setText(add1);
                String add2 = rs.getString("cell_phone");
                txt_vendor_phone.setText(add2);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_vendor_name_comboPopupMenuWillBecomeInvisible

    private void product_name_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_name_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_product_name_comboActionPerformed

    private void vendor_name_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendor_name_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendor_name_comboActionPerformed

    private void product_name_comboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_product_name_comboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String temp = (String) product_name_combo.getSelectedItem();
        String sql = "select * from product where p_name = ?";
        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, temp);
            rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("p_code");
                txt_product_code.setText(add1);
                String add2 = rs.getString("unit_price");
                txt_unit_price.setText(add2);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_product_name_comboPopupMenuWillBecomeInvisible

    private void txt_search_purchaseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_purchaseKeyReleased
        // TODO add your handling code here:

        try {

            String sql = "SELECT purchase_id as 'Purchase Id',"
                    + " product_code as 'Product Code', " + "product_name as 'Product Name',"
                    + " date as 'Date', "
                    + "total as 'Total' FROM purchases WHERE purchase_id = ? or product_code = ? or invoice_id = ? or product_name = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_search_purchase.getText());
            pst.setString(2, txt_search_purchase.getText());
            pst.setString(3, txt_search_purchase.getText());
            pst.setString(4, txt_search_purchase.getText());
            rs = pst.executeQuery();
            purchase_view_table.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }

        clear();

    }//GEN-LAST:event_txt_search_purchaseKeyReleased

    private void txt_search_purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search_purchaseActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txt_search_purchaseActionPerformed

    private void btn_add_product_purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_product_purchaseActionPerformed
        // TODO add your handling code here:

        String address = txt_vendor_address.getText();
        String phone = txt_vendor_phone.getText();
        String quantity = txt_unit_price.getText();
        String total = txt_total.getText();

        if (quantity.equals("")) {
            JOptionPane.showMessageDialog(null, "Please Insert detials Information first!!.");
        } else if (total.equals("")) {
            JOptionPane.showMessageDialog(null, "Please Insert detials Information first!!.");
        } else if (address.equals("")) {
            JOptionPane.showMessageDialog(null, "Please Insert detials Information first!!.");
        } else {
            Object[] column = {"Date", "Vendor Name", "Address", "Phone", "Product Name", "Product Code", "Quantity", "Unit_price", "Total", "Note"};
            try {

                DefaultTableModel model = (DefaultTableModel) multiple_add_purchase_table.getModel();
                model.setColumnIdentifiers(column);
                Object[] row = new Object[10];
                row[0] = ((JTextField) txt_purchase_date.getDateEditor().getUiComponent()).getText();
                row[1] = vendor_name_combo.getSelectedItem();
                row[2] = txt_vendor_address.getText();
                row[3] = txt_vendor_phone.getText();
                row[4] = product_name_combo.getSelectedItem();
                row[5] = txt_product_code.getText();
                row[6] = txt_quantity.getText();
                row[7] = txt_unit_price.getText();
                row[8] = txt_total.getText();
                row[9] = txt_note.getText();
                model.addRow(row);

            } catch (Exception e) {

                e.getMessage();
            }

            //getSum();
            total_column_price.setText(Integer.toString(getSum()));
            clear();
            VendorFillCombo();
            ProductFillCombo();
        }

    }//GEN-LAST:event_btn_add_product_purchaseActionPerformed

    private void total_column_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_column_priceActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_total_column_priceActionPerformed

    private void total_column_priceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total_column_priceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_column_priceKeyPressed

    private void total_column_priceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_total_column_priceMouseClicked
        // TODO add your handling code here:

        total_column_price.setText(Integer.toString(getSum()));

    }//GEN-LAST:event_total_column_priceMouseClicked

    private void btn_delete_multiple_jtableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_multiple_jtableActionPerformed
        // TODO add your handling code here:
        int i = multiple_add_purchase_table.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) multiple_add_purchase_table.getModel();
        if (i >= 0) {
            model.removeRow(i);
        } else {
            System.out.println("Delete Error");
        }

    }//GEN-LAST:event_btn_delete_multiple_jtableActionPerformed

    private void txt_search_purchaseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_search_purchaseFocusLost
        // TODO add your handling code here:
        hint.hint_text(txt_search_purchase, hint.getPurchase_search(), txt_search_purchase.getText().trim().length());

    }//GEN-LAST:event_txt_search_purchaseFocusLost

    private void txt_search_purchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_search_purchaseMouseClicked
        // TODO add your handling code here:
        hint.clcik(txt_search_purchase, hint.getPurchase_search());


    }//GEN-LAST:event_txt_search_purchaseMouseClicked

    private void txt_quantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quantityKeyReleased
        // TODO add your handling code here:
        txt_total.setText("");
        total_price();
    }//GEN-LAST:event_txt_quantityKeyReleased

    public int removeitem() {
        int i = multiple_add_purchase_table.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) multiple_add_purchase_table.getModel();
        if (i >= 0) {
            model.removeRow(i);
        } else {
            System.out.println("Delete Error");
        }
        return 0;
    }

    public int getSum() {
        int rowcount = multiple_add_purchase_table.getRowCount();
        int sum = 0;
        for (int i = 0; i < rowcount; i++) {
            sum = sum + Integer.parseInt(multiple_add_purchase_table.getValueAt(i, 8).toString());
        }
        return sum;
    }

    private void clear() {
        vendor_name_combo.setToolTipText("");
        txt_vendor_address.setText("");
        txt_vendor_phone.setText("");
        product_name_combo.setToolTipText("");
        txt_product_code.setText("");
        txt_unit_price.setText("");
        txt_quantity.setText("");
        txt_total.setText("");
        txt_note.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {

        } catch (InstantiationException ex) {

        } catch (IllegalAccessException ex) {

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Test_PurchaseJFrame_Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_product_purchase;
    private javax.swing.JButton btn_delete_multiple_jtable;
    private javax.swing.JButton btn_delete_purchase;
    private javax.swing.JButton btn_save_purchase;
    private javax.swing.JButton btn_update_purchase;
    private javax.swing.JButton btn_view_purchase;
    private javax.swing.JButton cmd_add_product;
    private javax.swing.JButton cmd_add_vendor;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable multiple_add_purchase_table;
    private javax.swing.JComboBox<String> product_name_combo;
    private javax.swing.JTable purchase_view_table;
    private javax.swing.JTextField total_column_price;
    private javax.swing.JTextField txt_note;
    private javax.swing.JTextField txt_product_code;
    private com.toedter.calendar.JDateChooser txt_purchase_date;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_search_purchase;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_unit_price;
    private javax.swing.JTextField txt_vendor_address;
    private javax.swing.JTextField txt_vendor_phone;
    private javax.swing.JComboBox<String> vendor_name_combo;
    // End of variables declaration//GEN-END:variables
}
